services:
  - type: web
    name: pricepulse-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      playwright install
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    workingDir: backend
